import type {
  Achievement,
  Agent,
  Mission,
  ReportData,
  VentureBrief,
} from './types'

export const defaultBrief: VentureBrief = {
  businessIdea: "Service d'audit de visibilité IA",
  targetCustomer: 'Entreprises SaaS B2B en France',
  existingAssets: "Profil finance, expérience SaaS IA, compétences d'analyse marché",
  startingBudget: '€500',
  timePerWeek: '10 heures',
  mainObjective: 'Obtenir 3 appels découverte en 14 jours',
  currentStage: 'Idée avec expertise fondateur',
  tone: 'Analytique, direct, premium, sans bullshit',
  autonomy: 'Validation requise',
}

export const missions: Mission[] = [
  {
    id: 'm1',
    index: 1,
    title: "Scan d'opportunité",
    type: 'Marché',
    reward: '+25 Connaissance marché',
    output: "Rapport d'opportunité",
    energyCost: 8,
    risk: 'Low',
    rarity: 'Rare',
    description: "Cartographier le marché, valider le pain client et qualifier l'opportunité.",
    estimatedTime: '4 min',
    expectedResult: "Rapport d'opportunité + score de priorité",
    difficulty: 'Facile',
    impact: '+12% maturité Analyse',
    assignedAgentIds: ['strategist', 'analyst'],
  },
  {
    id: 'm2',
    index: 2,
    title: 'Positionnement',
    type: 'Stratégie',
    reward: '+30 Clarté produit',
    output: 'Brief de positionnement',
    required: "Scan d'opportunité approuvé",
    energyCost: 10,
    risk: 'Low',
    rarity: 'Rare',
    description: "Définir l'ICP, la catégorie et la promesse centrale à partir du scan.",
    estimatedTime: '5 min',
    expectedResult: 'ICP, catégorie et message test',
    difficulty: 'Intermédiaire',
    impact: '+15% clarté business',
    assignedAgentIds: ['strategist', 'offer-architect'],
  },
  {
    id: 'm3',
    index: 3,
    title: "Construction de l'offre",
    type: 'Monétisation',
    reward: '+35 Clarté produit',
    output: 'Offre de service & pricing',
    required: 'Positionnement approuvé',
    energyCost: 12,
    risk: 'Medium',
    rarity: 'Epic',
    description: 'Packager les livrables, le pricing, la garantie et le traitement des objections.',
    estimatedTime: '6 min',
    expectedResult: "Offre, pricing et objections commerciales",
    difficulty: 'Intermédiaire',
    impact: '+18% maturité Monétisation',
    assignedAgentIds: ['offer-architect', 'strategist'],
  },
  {
    id: 'm4',
    index: 4,
    title: 'Kit de marque',
    type: 'Marque',
    reward: '+30 Force de marque',
    output: 'Nom, accroche & ton',
    required: 'Offre approuvée',
    energyCost: 9,
    risk: 'Medium',
    rarity: 'Epic',
    description: "Transformer l'offre en nom, accroche et direction de marque cohérente.",
    estimatedTime: '4 min',
    expectedResult: 'Nom, accroche et ton de marque',
    difficulty: 'Facile',
    impact: '+14% maturité Contenu',
    assignedAgentIds: ['brand-builder'],
  },
  {
    id: 'm5',
    index: 5,
    title: 'Landing Page',
    type: 'Asset',
    reward: '+1 asset business',
    output: 'Copywriting landing page',
    required: 'Kit de marque approuvé',
    energyCost: 14,
    risk: 'Medium',
    rarity: 'Epic',
    description: 'Assembler la première landing orientée conversion à partir du kit de marque.',
    estimatedTime: '7 min',
    expectedResult: 'Blueprint complet de landing page',
    difficulty: 'Avancé',
    impact: '+20% conversion préparée',
    assignedAgentIds: ['brand-builder', 'growth-op'],
  },
  {
    id: 'm6',
    index: 6,
    title: "Plan d'acquisition",
    type: 'Croissance',
    reward: "+35 Puissance d'acquisition",
    output: "Plan 14 jours",
    required: 'Landing page approuvée',
    energyCost: 12,
    risk: 'High',
    rarity: 'Epic',
    description: 'Transformer la landing en plan de canaux et outbound sur 14 jours.',
    estimatedTime: '6 min',
    expectedResult: "Plan d'acquisition 14 jours + KPI",
    difficulty: 'Avancé',
    impact: '+22% maturité Acquisition',
    assignedAgentIds: ['growth-op', 'analyst'],
  },
  {
    id: 'm7',
    index: 7,
    title: 'Test de lancement',
    type: 'Exécution',
    reward: '+Traction',
    output: 'Pack prospects + messages',
    required: "Plan d'acquisition approuvé",
    energyCost: 16,
    risk: 'High',
    rarity: 'Legendary',
    description: "Étape finale : préparer prospects, messages et tracker pour le premier test marché.",
    estimatedTime: '8 min',
    expectedResult: 'Pack prospects, messages et règles de décision',
    difficulty: 'Avancé',
    impact: '+25% traction activable',
    assignedAgentIds: ['growth-op', 'strategist'],
  },
]

export const agents: Agent[] = [
  {
    id: 'strategist',
    name: 'Stratège',
    className: 'Stratégie',
    role: 'Stratégie business et logique de décision',
    department: 'Stratégie',
    reliability: 84,
    unlockAfter: 0,
    level: 3,
    mission: 'Priorise les décisions qui font avancer le venture sans dispersion.',
    result: 'Recommandations, arbitrages et feuille de route',
    avatar: {
      initials: 'ST',
      color: 'indigo',
      accessory: 'Carte mentale',
      workspace: 'Tableau de décision',
    },
    personality: 'Calme, synthétique, orienté décision',
    skills: ['Positionnement', 'Priorisation', 'Risques'],
    recommendation: 'Lui confier les missions avec risque stratégique ou arbitrage marché.',
    recentHistory: [
      "A cadré l'opportunité initiale",
      'A détecté les risques de perception nice-to-have',
      'A recommandé le segment SaaS B2B prioritaire',
    ],
    stats: { Logique: 88, Créativité: 72, Exécution: 65, Risque: 74 },
  },
  {
    id: 'analyst',
    name: 'Analyste Marché',
    className: 'Recherche',
    role: 'Étude marché et cartographie concurrents',
    department: 'Stratégie',
    reliability: 81,
    unlockAfter: 0,
    level: 2,
    mission: 'Analyse les signaux marché, les concurrents et les patterns de demande.',
    result: 'Segments, alternatives concurrentes et insights exploitables',
    avatar: {
      initials: 'AM',
      color: 'cyan',
      accessory: 'Graphique',
      workspace: 'Écran benchmark',
    },
    personality: 'Précis, curieux, orienté preuve',
    skills: ['Recherche', 'Benchmark', 'Scoring'],
    recommendation: 'À activer avant les décisions de positionnement ou acquisition.',
    recentHistory: [
      'A cartographié les alternatives concurrentes',
      'A isolé les signaux de pain client',
      "A enrichi le score d'opportunité",
    ],
    stats: { Recherche: 86, Patterns: 80, Précision: 76, Vitesse: 69 },
  },
  {
    id: 'offer-architect',
    name: "Architecte d'Offre",
    className: 'Monétisation',
    role: 'Packaging, pricing et traitement des objections',
    department: 'Finance',
    reliability: 86,
    unlockAfter: 2,
    level: 2,
    mission: "Transforme l'expertise en offre vendable, claire et testable.",
    result: 'Offre packagée, hypothèse de prix et garantie',
    avatar: {
      initials: 'AO',
      color: 'emerald',
      accessory: 'Calculatrice',
      workspace: 'Table de pricing',
    },
    personality: 'Structuré, commercial, attentif à la valeur',
    skills: ['Pricing', 'Packaging', 'Objections'],
    recommendation: 'À améliorer dès que les premiers retours prospects arrivent.',
    recentHistory: [
      'A préparé une hypothèse de prix founder-friendly',
      'A clarifié les livrables du sprint',
      'A formulé une garantie de réduction du risque',
    ],
    stats: { Valeur: 90, Pricing: 82, Vente: 76, Clarté: 88 },
  },
  {
    id: 'brand-builder',
    name: 'Brand Builder',
    className: 'Marque',
    role: "Naming, messaging et direction d'identité",
    department: 'Marketing',
    reliability: 78,
    unlockAfter: 3,
    level: 2,
    mission: 'Crée les messages et assets qui rendent le business lisible.',
    result: 'Kit de marque, landing et angles de contenu',
    avatar: {
      initials: 'BB',
      color: 'violet',
      accessory: 'Clavier',
      workspace: 'Studio contenu',
    },
    personality: 'Éditorial, direct, sensible au ton premium',
    skills: ['Copy', 'Naming', 'Landing'],
    recommendation: 'Lui assigner les missions où la clarté perçue bloque la conversion.',
    recentHistory: [
      'A défini un ton analytique et direct',
      'A proposé une direction visuelle diagnostic premium',
      'A structuré le blueprint de landing',
    ],
    stats: { Copy: 86, Goût: 78, Voix: 80, Vitesse: 72 },
  },
  {
    id: 'growth-op',
    name: 'Opérateur Croissance',
    className: 'Croissance',
    role: 'Acquisition, plan de campagne et exécution',
    department: 'Acquisition',
    reliability: 82,
    unlockAfter: 5,
    level: 2,
    mission: 'Transforme les assets validés en actions de prospection mesurables.',
    result: 'Plan acquisition, prospects, messages et tracker',
    avatar: {
      initials: 'OC',
      color: 'amber',
      accessory: 'CRM',
      workspace: 'Console outbound',
    },
    personality: 'Cadencé, pragmatique, obsédé par les KPI',
    skills: ['Outbound', 'Canaux', 'KPI'],
    recommendation: "À lancer quand l'offre et la landing sont suffisamment stables.",
    recentHistory: [
      "A préparé le rythme d'acquisition 14 jours",
      'A défini les critères prospects',
      'A construit les variantes de messages',
    ],
    stats: { Leads: 82, Canaux: 74, Outbound: 86, Ops: 78 },
  },
]

export const executionSteps = [
  'Lecture du brief projet',
  'Analyse du contexte',
  'Identification des leviers',
  'Évaluation des risques',
  'Rédaction du livrable',
]

export const executionLogs = [
  "Stratège : conversion de l'idée en hypothèses business...",
  'Analyste Marché : identification des segments clients...',
  'Analyste Marché : cartographie des alternatives existantes...',
  "Stratège : évaluation de l'attractivité de l'opportunité...",
  'Analyste Marché : détection des angles de différenciation...',
  'Stratège : préparation de la recommandation finale...',
  'Livrable prêt pour validation.',
]

export const reports: Record<string, ReportData> = {
  m1: {
    missionId: 'm1',
    title: "Rapport d'opportunité",
    subtitle: "Pain marché, ICP, alternatives concurrentes et score d'opportunité.",
    qualityScore: 82,
    authors: 'Stratège + Analyste Marché',
    approveLabel: 'Approuver le rapport',
    sections: [
      {
        title: 'Résumé exécutif',
        body: (b) =>
          `${b.businessIdea} cible ${b.targetCustomer}. Stade actuel : ${b.currentStage}, avec ${b.startingBudget} de budget et ${b.timePerWeek} disponibles par semaine. La validité de l'opportunité dépend de la capacité à atteindre l'objectif : ${b.mainObjective}.`,
      },
      {
        title: 'Meilleur client initial',
        body: (b) =>
          `${b.targetCustomer}. C'est le premier segment à tester : les assets fondateur (${b.existingAssets}) peuvent être convertis en première offre crédible.`,
      },
      {
        title: 'Angle stratégique',
        body: (b) =>
          `Sortir du wording générique. Utiliser un angle "risque acheteur" concret : voir si ${b.businessIdea.toLowerCase()} peut résoudre un problème mesurable pour ${b.targetCustomer}. Ton : ${b.tone.toLowerCase()}.`,
      },
      {
        title: 'Première offre recommandée',
        body: (b) =>
          `Sprint focalisé autour de ${b.businessIdea}. Suffisamment étroit pour être livré avec ${b.timePerWeek}/semaine et testable dans la limite de ${b.startingBudget}.`,
      },
      {
        title: 'Risques clés',
        body: () =>
          "Éducation marché nécessaire. Risque que l'offre soit perçue comme un nice-to-have. Crédibilité méthodologique critique.",
      },
      {
        title: 'Recommandation',
        body: () =>
          'Passer à la mission 2 : Positionnement. Priorité aux acheteurs qui comprennent déjà le problème.',
      },
    ],
  },
  m2: {
    missionId: 'm2',
    title: 'Brief de positionnement',
    subtitle: 'ICP, catégorie, promesse centrale et premier message test.',
    qualityScore: 86,
    authors: "Stratège + Architecte d'Offre",
    approveLabel: 'Approuver le positionnement',
    sections: [
      { title: 'ICP', body: (b) => `${b.targetCustomer}. Priorité aux acheteurs avec une raison urgente de tester ${b.businessIdea.toLowerCase()}.` },
      { title: 'Catégorie', body: (b) => `${b.businessIdea}. La catégorie doit être compréhensible en moins de 10 secondes par ${b.targetCustomer}.` },
      { title: 'Promesse centrale', body: (b) => `Aider ${b.targetCustomer} à atteindre "${b.mainObjective}" en transformant ${b.businessIdea.toLowerCase()} en asset business concret.` },
      { title: 'Premier message test', body: (b) => `"Je teste ${b.businessIdea.toLowerCase()} pour ${b.targetCustomer}. Objectif : ${b.mainObjective.toLowerCase()}. Je vous envoie la première version pour feedback ?"` },
      { title: 'Prochaine mission', body: () => "Passer à la construction de l'offre : livrables, pricing, garantie, traitement des objections." },
    ],
  },
  m3: {
    missionId: 'm3',
    title: "Pack d'offre",
    subtitle: 'Nom, livrables, pricing, garantie et traitement des objections.',
    qualityScore: 88,
    authors: "Stratège + Architecte d'Offre",
    approveLabel: "Approuver l'offre",
    sections: [
      { title: "Nom de l'offre", body: (b) => `${b.businessIdea} Sprint — pack focalisé pour ${b.targetCustomer}, calibré pour ${b.timePerWeek}/semaine et l'objectif "${b.mainObjective}".` },
      { title: 'Livrables clés', body: (b) => `Appel de découverte, scorecard de diagnostic, recommandations concrètes, priorités d'implémentation, plan d'étape suivant. Basé sur les assets fondateur : ${b.existingAssets}.` },
      { title: 'Hypothèse de prix', body: (b) => `Premier prix sans friction relative à ${b.startingBudget} : pilote founder-friendly d'abord, puis montée en prix une fois la preuve établie.` },
      { title: 'Garantie / réduction du risque', body: () => "Si le diagnostic ne met pas en évidence au moins 5 angles concrets, dataset prompts + carte concurrents + 2e tour gratuit après améliorations." },
      { title: 'Objections commerciales', body: () => "\"C'est trop tôt\" → competitive intelligence, pas un nouveau canal. \"On fait déjà du SEO\" → les réponses IA synthétisent autrement. \"Nice to have\" → mener avec le risque concurrentiel." },
      { title: 'Prochaine mission', body: () => 'Passer au kit de marque : nom, accroche, ton et direction de landing page.' },
    ],
  },
  m4: {
    missionId: 'm4',
    title: 'Kit de marque',
    subtitle: 'Nom, accroche, ton de voix et direction visuelle.',
    qualityScore: 85,
    authors: 'Brand Builder',
    approveLabel: 'Approuver le kit',
    sections: [
      { title: 'Nom recommandé', body: (_b, name) => `${name}. Fonctionnel et confiance-first pour le premier test. Doit expliquer l'activité sans sonner agence IA vague.` },
      { title: 'Accroche', body: (b) => `"${b.businessIdea} pour ${b.targetCustomer}." Optimisation pour la compréhension, pas la cleverness.` },
      { title: 'Ton de voix', body: (b) => `${b.tone}. Éviter la hype. Constats concrets, captures, scorecards, règles de décision claires.` },
      { title: 'Direction visuelle', body: () => 'Interface diagnostic premium clair : fond très clair, accent indigo, état succès vert, cartes type rapport, scorecards et grilles de benchmark.' },
      { title: 'Règles de message landing', body: () => 'Mener avec le risque et la curiosité, puis la méthodologie. Pas de "agence GEO". Plutôt "audit de visibilité IA pour équipes SaaS B2B". Proof blocks : prompts testés, moteurs couverts, concurrents benchmarkés.' },
      { title: 'Prochaine mission', body: () => 'Passer à la landing page : hero, problème, méthodologie, livrables, CTA pricing.' },
    ],
  },
  m5: {
    missionId: 'm5',
    title: 'Blueprint de landing page',
    subtitle: 'Hero, problème, méthodologie, livrables, CTA pricing.',
    qualityScore: 87,
    authors: 'Brand Builder + Opérateur Croissance',
    approveLabel: 'Approuver la landing page',
    sections: [
      { title: 'Section hero', body: (b) => `Headline : "${b.businessIdea} pour ${b.targetCustomer}." Subheadline : "Construit pour atteindre : ${b.mainObjective}." CTA primaire : "Demander la première version".` },
      { title: 'Section problème', body: (b) => `Le test doit prouver l'urgence : rendre concret le coût de l'inaction et le relier à ${b.mainObjective.toLowerCase()}.` },
      { title: 'Section méthodologie', body: () => "Quatre blocs : design des prompts, test moteurs IA, benchmark concurrents, rapport d'écart de visibilité." },
      { title: 'Section livrables', body: () => 'Scorecard visibilité, carte des recommandations concurrents, findings de misreprésentation, dataset de prompts, plan d\'action priorisé, appel de revue 30min.' },
      { title: 'CTA pricing', body: () => 'Premiers clients : €750 audit fixe. CTA : "Obtenir un snapshot 48h". Secondaire : "Voir la structure d\'un rapport type".' },
      { title: 'Prochaine mission', body: () => "Passer au plan d'acquisition : canaux prioritaires, rythme outbound, KPI cibles." },
    ],
    footer: ['Hero', 'Problème', 'Méthodologie', 'Livrables', 'CTA pricing'],
  },
  m6: {
    missionId: 'm6',
    title: "Plan d'acquisition 14 jours",
    subtitle: 'Canaux prioritaires, rythme outbound, KPI cibles.',
    qualityScore: 89,
    authors: 'Opérateur Croissance',
    approveLabel: 'Approuver le plan',
    sections: [
      { title: 'Canal prioritaire', body: (b) => `Outbound LinkedIn mené par le fondateur + introductions chaudes. Cibler ${b.targetCustomer} en s'appuyant sur la crédibilité fondateur : ${b.existingAssets}.` },
      { title: 'Critères prospects', body: (b) => `Doit correspondre clairement à ${b.targetCustomer}, montrer des signaux de pain, décideur accessible, joignable avec ${b.timePerWeek}/semaine.` },
      { title: 'Rythme 14 jours', body: () => 'J1-2 : liste de 50 prospects. J3-8 : 10 messages personnalisés/jour. J9-11 : relance avec un finding concret. J12-14 : booker les appels, documenter les objections, décider scale ou pivot.' },
      { title: 'Angle outbound', body: (b) => `"Je teste ${b.businessIdea.toLowerCase()} pour des équipes comme la vôtre. Objectif : ${b.mainObjective.toLowerCase()}. Un snapshot court serait utile ?"` },
      { title: 'Objectifs KPI', body: () => '50 prospects · 35 deliveries · 8 réponses · 3 appels. Kill ou pivot si réponses < 10% après 50 prospects pertinents.' },
      { title: 'Prochaine mission', body: () => 'Passer au test de lancement : fichier prospects, messages outbound, règles de suivi.' },
    ],
  },
  m7: {
    missionId: 'm7',
    title: 'Pack de test de lancement',
    subtitle: 'Fichier prospects, messages, règles de décision go/no-go.',
    qualityScore: 91,
    authors: 'Opérateur Croissance + Stratège',
    approveLabel: 'Approuver le pack de lancement',
    sections: [
      { title: 'Objectif du test', body: (b) => `Valider que ${b.targetCustomer} considère ${b.businessIdea.toLowerCase()} suffisamment pour répondre, demander un sample, et avancer vers : ${b.mainObjective}.` },
      { title: 'Colonnes du fichier prospects', body: () => 'Entreprise, site web, segment, décideur, rôle, URL LinkedIn, concurrent probable, hypothèse de pain, variante message, statut, réponse, objection, prochaine action.' },
      { title: 'Message LinkedIn', body: (b) => `"Question rapide — êtes-vous en train de chercher à atteindre ${b.mainObjective.toLowerCase()} ? Je teste ${b.businessIdea.toLowerCase()} pour ${b.targetCustomer}. Je vous envoie un snapshot court ?"` },
      { title: 'Variante email', body: (b) => `Objet : "Idée pour ${b.targetCustomer}". Corps : "Je teste ${b.businessIdea.toLowerCase()} et cherche des retours de profils proches du vôtre. Je peux envoyer une version courte centrée sur ${b.mainObjective.toLowerCase()}."` },
      { title: 'Règle de décision', body: () => 'Continuer si 3+ appels bookés ou 8+ réponses qualifiées sur 50 prospects. Pivoter si les réponses montrent de la confusion. Arrêter si l\'audience comprend mais ne s\'y intéresse pas.' },
    ],
    footer: ['50 prospects', '2 variantes', '3 appels visés', 'fenêtre 14 jours'],
  },
}

export const achievements: Achievement[] = [
  { id: 'a1', title: 'Premier rapport', description: "Validé le rapport d'opportunité.", unlockAt: 1 },
  { id: 'a2', title: 'Positionné', description: 'Définit ICP, catégorie et promesse.', unlockAt: 2 },
  { id: 'a3', title: 'Offre packagée', description: 'Livrables, pricing et garantie.', unlockAt: 3 },
  { id: 'a4', title: 'Marque cadrée', description: 'Nom, accroche et ton clairs.', unlockAt: 4 },
  { id: 'a5', title: 'Asset en ligne', description: 'Première landing prête.', unlockAt: 5 },
  { id: 'a6', title: 'Plan opérationnel', description: '14 jours bien cadrés.', unlockAt: 6 },
  { id: 'a7', title: 'Premier test marché', description: 'Boucle complète parcourue.', unlockAt: 7 },
]

export function deriveVentureName(idea: string): string {
  const cleaned = idea.trim()
  if (!cleaned) return 'Nouveau Venture'
  const stopWords = ['service', 'platform', 'tool', 'app', 'business', 'for', 'the', 'a', 'an', 'de', 'la', "d'", 'du', 'des']
  const parts = cleaned
    .split(/\s+/)
    .filter((w) => !stopWords.includes(w.toLowerCase()))
    .slice(0, 2)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
  return parts.join(' ') + ' Lab'
}
