import type {
  Badge,
  GamAgent,
  GamMission,
  HQLevel,
  Skin,
} from './types'

export const hqLevels: HQLevel[] = [
  {
    level: 1,
    name: 'Idée brute',
    description: 'Vous arrivez avec une idée encore floue à structurer.',
    xpRequired: 0,
    unlockedFeatures: ['Agent Stratège', 'Premier brief projet', 'Carte de mission'],
    completionCriteria: [
      'Problème défini',
      'Cible identifiée',
      'Promesse formulée',
      'Nom de projet choisi',
    ],
  },
  {
    level: 2,
    name: 'Concept validé',
    description: 'Le projet commence à avoir une direction claire et testable.',
    xpRequired: 200,
    unlockedFeatures: [
      'Agent Étude de marché',
      'Agent Branding',
      'Tableau de bord de progression',
    ],
    completionCriteria: [
      'Persona défini',
      'Concurrents identifiés',
      'Proposition de valeur formulée',
      'Première offre brouillon',
    ],
  },
  {
    level: 3,
    name: 'Offre construite',
    description: 'Vous disposez d’une offre claire et vendable.',
    xpRequired: 500,
    unlockedFeatures: [
      'Agent Copywriting',
      'Agent Pricing',
      'Agent Landing Page',
      'Bibliothèque de livrables',
    ],
    completionCriteria: [
      'Offre claire',
      'Prix défini',
      'Bénéfices formulés',
      'Objections identifiées',
      'Landing page générée',
    ],
  },
  {
    level: 4,
    name: 'Mise sur le marché',
    description: 'Le projet sort de la théorie et passe en test marché.',
    xpRequired: 900,
    unlockedFeatures: [
      'Agent Acquisition',
      'Agent Sales',
      'Agent Contenu',
      'CRM simplifié',
    ],
    completionCriteria: [
      'Canal d’acquisition choisi',
      'Campagne lancée',
      'Premiers leads collectés',
      'Premiers messages envoyés',
    ],
  },
  {
    level: 5,
    name: 'Premiers revenus',
    description: 'Première preuve économique : ça génère du chiffre.',
    xpRequired: 1700,
    unlockedFeatures: [
      'Agent Customer Success',
      'Agent Analytics',
      'Agent Optimisation',
      'Suivi revenus / conversion',
    ],
    completionCriteria: [
      'Premier client',
      'Premier paiement',
      'Conversion suivie',
      'Retour client documenté',
    ],
  },
  {
    level: 6,
    name: 'Business en croissance',
    description: 'Vous pilotez une activité répétable et en croissance.',
    xpRequired: 2950,
    unlockedFeatures: [
      'Automatisations avancées',
      'Workflows multi-agents',
      'Reporting business',
      'Playbooks de croissance',
    ],
    completionCriteria: [
      'Revenus récurrents',
      'Acquisition répétable',
      'Offre améliorée',
      'Process documentés',
    ],
  },
]

export const gamAgents: GamAgent[] = [
  {
    id: 'strategist',
    name: 'Stratège',
    role: 'Clarifie l’idée, le problème, la cible, la vision.',
    level: 1,
    xp: 0,
    xpToNextLevel: 100,
    status: 'idle',
    activeSkinId: 'agent-default',
    unlockedSkinIds: ['agent-default'],
    accent: '#6c6ce3',
    icon: 'compass',
    hqLevelRequired: 1,
  },
  {
    id: 'market',
    name: 'Étude de marché',
    role: 'Identifie concurrents, opportunités, risques marché.',
    level: 1,
    xp: 0,
    xpToNextLevel: 100,
    status: 'locked',
    activeSkinId: 'agent-default',
    unlockedSkinIds: ['agent-default'],
    accent: '#1aa6a6',
    icon: 'search',
    hqLevelRequired: 2,
  },
  {
    id: 'branding',
    name: 'Branding',
    role: 'Nom, positionnement, ton de marque, identité narrative.',
    level: 1,
    xp: 0,
    xpToNextLevel: 100,
    status: 'locked',
    activeSkinId: 'agent-default',
    unlockedSkinIds: ['agent-default'],
    accent: '#f472b6',
    icon: 'palette',
    hqLevelRequired: 2,
  },
  {
    id: 'product',
    name: 'Offre / Product',
    role: 'Construit l’offre, bénéfices, proposition de valeur.',
    level: 1,
    xp: 0,
    xpToNextLevel: 100,
    status: 'locked',
    activeSkinId: 'agent-default',
    unlockedSkinIds: ['agent-default'],
    accent: '#f29d38',
    icon: 'package',
    hqLevelRequired: 3,
  },
  {
    id: 'pricing',
    name: 'Pricing',
    role: 'Définit prix, modèle économique, benchmark marché.',
    level: 1,
    xp: 0,
    xpToNextLevel: 100,
    status: 'locked',
    activeSkinId: 'agent-default',
    unlockedSkinIds: ['agent-default'],
    accent: '#fbbf24',
    icon: 'tag',
    hqLevelRequired: 3,
  },
  {
    id: 'landing',
    name: 'Landing Page',
    role: 'Structure et rédige la page de conversion.',
    level: 1,
    xp: 0,
    xpToNextLevel: 100,
    status: 'locked',
    activeSkinId: 'agent-default',
    unlockedSkinIds: ['agent-default'],
    accent: '#22d3ee',
    icon: 'layout',
    hqLevelRequired: 3,
  },
  {
    id: 'acquisition',
    name: 'Acquisition',
    role: 'Canaux, campagnes, messages, leads.',
    level: 1,
    xp: 0,
    xpToNextLevel: 100,
    status: 'locked',
    activeSkinId: 'agent-default',
    unlockedSkinIds: ['agent-default'],
    accent: '#40b77a',
    icon: 'megaphone',
    hqLevelRequired: 4,
  },
  {
    id: 'sales',
    name: 'Sales',
    role: 'Scripts de vente, objections, relances, conversion.',
    level: 1,
    xp: 0,
    xpToNextLevel: 100,
    status: 'locked',
    activeSkinId: 'agent-default',
    unlockedSkinIds: ['agent-default'],
    accent: '#ef4444',
    icon: 'handshake',
    hqLevelRequired: 4,
  },
  {
    id: 'content',
    name: 'Contenu',
    role: 'Posts, scripts vidéo, calendrier éditorial.',
    level: 1,
    xp: 0,
    xpToNextLevel: 100,
    status: 'locked',
    activeSkinId: 'agent-default',
    unlockedSkinIds: ['agent-default'],
    accent: '#a78bfa',
    icon: 'pen',
    hqLevelRequired: 4,
  },
  {
    id: 'analytics',
    name: 'Analytics',
    role: 'Métriques, performance, recommandations d’optimisation.',
    level: 1,
    xp: 0,
    xpToNextLevel: 100,
    status: 'locked',
    activeSkinId: 'agent-default',
    unlockedSkinIds: ['agent-default'],
    accent: '#60a5fa',
    icon: 'chart',
    hqLevelRequired: 5,
  },
]

export const gamMissions: GamMission[] = [
  {
    id: 'm1-clarify',
    title: 'Clarifier l’idée',
    description: 'Synthétiser le projet en une phrase claire et compréhensible.',
    agentId: 'strategist',
    status: 'available',
    xpReward: 50,
    expectedDeliverable: 'Pitch en une phrase',
    unlocks: ['m2-persona'],
    validationCriteria: ['Pitch < 25 mots', 'Problème explicite', 'Cible explicite'],
    hqLevelRequired: 1,
    dimension: 'clarity',
  },
  {
    id: 'm2-persona',
    title: 'Identifier une cible rentable',
    description: 'Définir 3 personas prioritaires avec besoins et budget.',
    agentId: 'market',
    status: 'locked',
    xpReward: 75,
    expectedDeliverable: '3 personas priorisés',
    unlocks: ['m3-competitors'],
    validationCriteria: ['3 personas', 'Critères de priorisation', 'Budget estimé'],
    hqLevelRequired: 1,
    dimension: 'clarity',
  },
  {
    id: 'm3-competitors',
    title: 'Analyser les concurrents',
    description: 'Identifier 5 concurrents directs et indirects et leur positionnement.',
    agentId: 'market',
    status: 'locked',
    xpReward: 75,
    expectedDeliverable: 'Tableau de 5 concurrents',
    unlocks: ['m4-value-prop'],
    badgeReward: 'b-competitors',
    validationCriteria: ['5 lignes', 'Forces / faiblesses', 'Prix indicatifs'],
    hqLevelRequired: 1,
    dimension: 'clarity',
  },
  {
    id: 'm4-value-prop',
    title: 'Formuler une proposition de valeur',
    description: 'Une promesse claire qui parle à votre cible prioritaire.',
    agentId: 'strategist',
    status: 'locked',
    xpReward: 100,
    expectedDeliverable: 'Proposition de valeur claire',
    unlocks: ['m5-offer'],
    validationCriteria: ['Pour qui', 'Quel bénéfice', 'Pourquoi vous'],
    hqLevelRequired: 2,
    dimension: 'offer',
  },
  {
    id: 'm5-offer',
    title: 'Construire la première offre',
    description: 'Assembler l’offre : cible, bénéfices, livrables, prix indicatif.',
    agentId: 'product',
    status: 'locked',
    xpReward: 100,
    expectedDeliverable: 'Offre structurée',
    unlocks: ['m6-pricing'],
    badgeReward: 'b-offer-built',
    validationCriteria: ['Bénéfices listés', 'Livrables clairs', 'Prix indicatif'],
    hqLevelRequired: 2,
    dimension: 'offer',
  },
  {
    id: 'm6-pricing',
    title: 'Définir le prix',
    description: 'Prix recommandé avec justification benchmark et logique de valeur.',
    agentId: 'pricing',
    status: 'locked',
    xpReward: 100,
    expectedDeliverable: 'Prix + justification',
    unlocks: ['m7-landing'],
    badgeReward: 'b-pricing',
    validationCriteria: ['Prix défini', 'Benchmark', 'Logique de valeur'],
    hqLevelRequired: 2,
    dimension: 'offer',
  },
  {
    id: 'm7-landing',
    title: 'Générer la landing page',
    description: 'Structure complète : hero, bénéfices, preuves, CTA.',
    agentId: 'landing',
    status: 'locked',
    xpReward: 150,
    expectedDeliverable: 'Structure de landing',
    unlocks: ['m8-publish'],
    badgeReward: 'b-landing-gen',
    validationCriteria: ['Hero', 'Bénéfices', 'CTA'],
    hqLevelRequired: 3,
    dimension: 'offer',
  },
  {
    id: 'm8-publish',
    title: 'Publier la landing page',
    description: 'Mettre la landing en ligne ou prête à publier.',
    agentId: 'landing',
    status: 'locked',
    xpReward: 250,
    expectedDeliverable: 'Landing publiée',
    unlocks: ['m9-channel'],
    badgeReward: 'b-landing-pub',
    validationCriteria: ['URL active', 'Tracking en place'],
    hqLevelRequired: 3,
    dimension: 'acquisition',
  },
  {
    id: 'm9-channel',
    title: 'Choisir un canal d’acquisition',
    description: 'Canal prioritaire + justification stratégique.',
    agentId: 'acquisition',
    status: 'locked',
    xpReward: 100,
    expectedDeliverable: 'Canal choisi',
    unlocks: ['m10-campaign'],
    badgeReward: 'b-channel',
    validationCriteria: ['Canal nommé', 'Justification', 'Objectif chiffré'],
    hqLevelRequired: 4,
    dimension: 'acquisition',
  },
  {
    id: 'm10-campaign',
    title: 'Lancer une campagne test',
    description: 'Messages + cible + canal + objectif mesurable.',
    agentId: 'acquisition',
    status: 'locked',
    xpReward: 200,
    expectedDeliverable: 'Campagne test active',
    unlocks: ['m11-first-lead'],
    validationCriteria: ['Messages', 'Cible', 'Budget / effort', 'KPI'],
    hqLevelRequired: 4,
    dimension: 'acquisition',
  },
  {
    id: 'm11-first-lead',
    title: 'Obtenir le premier lead',
    description: 'Lead qualifié ajouté au CRM.',
    agentId: 'acquisition',
    status: 'locked',
    xpReward: 200,
    expectedDeliverable: 'Lead qualifié',
    unlocks: ['m12-first-call'],
    badgeReward: 'b-first-lead',
    validationCriteria: ['Contact', 'Besoin identifié', 'Suite définie'],
    hqLevelRequired: 4,
    dimension: 'traction',
  },
  {
    id: 'm12-first-call',
    title: 'Obtenir le premier appel client',
    description: 'Call planifié ou réalisé avec un prospect qualifié.',
    agentId: 'sales',
    status: 'locked',
    xpReward: 300,
    expectedDeliverable: 'Call planifié / réalisé',
    unlocks: ['m13-first-client'],
    badgeReward: 'b-first-call',
    validationCriteria: ['Date du call', 'Compte-rendu', 'Prochaine étape'],
    hqLevelRequired: 4,
    dimension: 'traction',
  },
  {
    id: 'm13-first-client',
    title: 'Signer le premier client',
    description: 'Premier engagement client formalisé.',
    agentId: 'sales',
    status: 'locked',
    xpReward: 500,
    expectedDeliverable: 'Client signé',
    unlocks: ['m14-first-payment'],
    badgeReward: 'b-first-client',
    validationCriteria: ['Accord signé', 'Modalités définies'],
    hqLevelRequired: 5,
    dimension: 'traction',
  },
  {
    id: 'm14-first-payment',
    title: 'Recevoir le premier paiement',
    description: 'Premier euro reçu — preuve économique du projet.',
    agentId: 'sales',
    status: 'locked',
    xpReward: 750,
    expectedDeliverable: 'Paiement confirmé',
    badgeReward: 'b-first-euro',
    validationCriteria: ['Paiement reçu', 'Facture'],
    hqLevelRequired: 5,
    dimension: 'traction',
  },
]

export const badges: Badge[] = [
  {
    id: 'b-idea',
    name: 'Idée clarifiée',
    description: 'Vous avez transformé une intuition en pitch lisible.',
    unlocked: false,
    unlockCondition: 'Valider la mission “Clarifier l’idée”.',
    category: 'strategy',
    icon: 'flag',
  },
  {
    id: 'b-target',
    name: 'Cible identifiée',
    description: 'Personas priorisés et qualifiés.',
    unlocked: false,
    unlockCondition: 'Valider la mission “Identifier une cible rentable”.',
    category: 'strategy',
    icon: 'compass',
  },
  {
    id: 'b-competitors',
    name: 'Concurrents analysés',
    description: 'Vous savez face à qui vous jouez.',
    unlocked: false,
    unlockCondition: 'Compléter l’analyse concurrentielle.',
    category: 'strategy',
    icon: 'search',
  },
  {
    id: 'b-offer-built',
    name: 'Offre construite',
    description: 'Promesse, livrables et bénéfices structurés.',
    unlocked: false,
    unlockCondition: 'Construire la première offre.',
    category: 'offer',
    icon: 'package',
  },
  {
    id: 'b-pricing',
    name: 'Prix défini',
    description: 'Vous savez à combien vous vendez et pourquoi.',
    unlocked: false,
    unlockCondition: 'Valider la mission Pricing.',
    category: 'offer',
    icon: 'tag',
  },
  {
    id: 'b-landing-gen',
    name: 'Landing générée',
    description: 'Page structurée pour convertir.',
    unlocked: false,
    unlockCondition: 'Générer la landing page.',
    category: 'offer',
    icon: 'layout',
  },
  {
    id: 'b-landing-pub',
    name: 'Landing publiée',
    description: 'La promesse est désormais accessible publiquement.',
    unlocked: false,
    unlockCondition: 'Publier la landing page.',
    category: 'acquisition',
    icon: 'rocket',
  },
  {
    id: 'b-channel',
    name: 'Canal validé',
    description: 'Un canal d’acquisition priorisé et activé.',
    unlocked: false,
    unlockCondition: 'Choisir et lancer un canal.',
    category: 'acquisition',
    icon: 'megaphone',
  },
  {
    id: 'b-first-lead',
    name: 'Premier lead',
    description: 'Un humain a montré de l’intérêt.',
    unlocked: false,
    unlockCondition: 'Ajouter un premier lead qualifié.',
    category: 'acquisition',
    icon: 'flag',
  },
  {
    id: 'b-first-call',
    name: 'Premier call',
    description: 'Le marché vous accorde du temps.',
    unlocked: false,
    unlockCondition: 'Planifier ou réaliser un premier call.',
    category: 'sales',
    icon: 'handshake',
  },
  {
    id: 'b-first-client',
    name: 'Premier client',
    description: 'Quelqu’un s’engage avec vous.',
    unlocked: false,
    unlockCondition: 'Signer un premier client.',
    category: 'sales',
    icon: 'trophy',
  },
  {
    id: 'b-first-euro',
    name: 'Premier euro',
    description: 'Le projet existe économiquement.',
    unlocked: false,
    unlockCondition: 'Recevoir un premier paiement.',
    category: 'revenue',
    icon: 'wallet',
  },
  {
    id: 'b-1k',
    name: '1 000 € générés',
    description: 'Première marche de revenus consolidée.',
    unlocked: false,
    unlockCondition: 'Atteindre 1 000 € de revenus cumulés.',
    category: 'revenue',
    icon: 'crown',
  },
  {
    id: 'b-repeatable',
    name: 'Business répétable',
    description: 'Vous avez un système qui peut tourner.',
    unlocked: false,
    unlockCondition: 'Atteindre le niveau 6 du QG.',
    category: 'revenue',
    icon: 'trophy',
  },
]

export const skins: Skin[] = [
  // HQ skins
  {
    id: 'hq-garage',
    name: 'Garage',
    type: 'hq',
    targetId: '1',
    unlocked: true,
    unlockCondition: 'QG Niveau 1',
    rarity: 'common',
    description: 'Petit bureau, un tableau blanc, l’essentiel.',
  },
  {
    id: 'hq-studio',
    name: 'Studio',
    type: 'hq',
    targetId: '2',
    unlocked: false,
    unlockCondition: 'Atteindre QG Niveau 2',
    rarity: 'common',
    description: 'Premiers écrans, postes structurés.',
  },
  {
    id: 'hq-startup',
    name: 'Startup Office',
    type: 'hq',
    targetId: '3',
    unlocked: false,
    unlockCondition: 'Atteindre QG Niveau 3',
    rarity: 'rare',
    description: 'Espaces dédiés, bibliothèque de livrables.',
  },
  {
    id: 'hq-warroom',
    name: 'War Room',
    type: 'hq',
    targetId: '4',
    unlocked: false,
    unlockCondition: 'Atteindre QG Niveau 4',
    rarity: 'rare',
    description: 'Campagnes, leads, écrans d’acquisition.',
  },
  {
    id: 'hq-hub',
    name: 'Business Hub',
    type: 'hq',
    targetId: '5',
    unlocked: false,
    unlockCondition: 'Atteindre QG Niveau 5',
    rarity: 'epic',
    description: 'Pipeline clients, dashboards, revenus.',
  },
  {
    id: 'hq-company',
    name: 'Company HQ',
    type: 'hq',
    targetId: '6',
    unlocked: false,
    unlockCondition: 'Atteindre QG Niveau 6',
    rarity: 'legendary',
    description: 'Départements, automatisations, reporting avancé.',
  },
  // Agent skins (common to all)
  {
    id: 'agent-default',
    name: 'Default',
    type: 'agent',
    unlocked: true,
    unlockCondition: 'Disponible par défaut',
    rarity: 'common',
    description: 'Tenue standard de QG.',
  },
  // Métier skins per agent
  {
    id: 'skin-sales-closer',
    name: 'Closer',
    type: 'agent',
    targetId: 'sales',
    unlocked: false,
    unlockCondition: 'Signer le premier client.',
    rarity: 'epic',
    description: 'Tenue de closer pour finaliser les deals.',
  },
  {
    id: 'skin-acq-growth',
    name: 'Growth Operator',
    type: 'agent',
    targetId: 'acquisition',
    unlocked: false,
    unlockCondition: 'Obtenir 10 leads.',
    rarity: 'rare',
    description: 'Outils de growth déployés.',
  },
  {
    id: 'skin-product-architect',
    name: 'Architecte Produit',
    type: 'agent',
    targetId: 'product',
    unlocked: false,
    unlockCondition: 'Construire une offre complète.',
    rarity: 'rare',
    description: 'Schémas, post-its, prototype.',
  },
  {
    id: 'skin-pricing-finance',
    name: 'Finance',
    type: 'agent',
    targetId: 'pricing',
    unlocked: false,
    unlockCondition: 'Recevoir le premier paiement.',
    rarity: 'epic',
    description: 'Tableurs, calculatrice, graphiques.',
  },
  {
    id: 'skin-strategist-cyber',
    name: 'Cyber',
    type: 'agent',
    targetId: 'strategist',
    unlocked: false,
    unlockCondition: 'Atteindre QG Niveau 4',
    rarity: 'rare',
    description: 'Tableau holographique, vision augmentée.',
  },
]
